### ISSUE TITLE
Cannot start Songpress 1.7.2: Decimal separator mismatch

### ISSUE THREAD

**Issue by lallulli** [lallulli/songpress#38]
Reported bug

```
#---- System Information ----#
Songpress Version: 1.7.2
Operating System: Windows 7 (build 7601, Service Pack 1), édition 64-bit
Python Version: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
wxPython Version: 4.0.4 msw (phoenix) wxWidgets 3.0.5
wxPython Info: (__WXMSW__, wxMSW, unicode, unicode-wchar, wx-assertions-on, phoenix, wxWidgets 3.0.5, autoidman, sip-4.19.13, build-type: release)
Python Encoding: Default=utf-8 File=utf-8
System Architecture: 32bit AMD64
Byte order: little
Frozen: True
#---- End System Information ----#

#---- Traceback Info ----#
*** Sun Mar 10 14:11:45 2019 ***
Traceback (most recent call last):
File "main.py", line 32, in OnInit
File "C:\Users\Luca Allulli\Documents\dev\songpress\master\src\SongpressFrame.py", line 270, in __init__
File "C:\Users\Luca Allulli\Documents\dev\songpress\master\src\SongpressFrame.py", line 400, in AddTool
wx._core.wxAssertionError: C++ assertion "wxString::Format("%.3f", 1.23).find(str) != wxString::npos" failed at ..\..\src\common\intl.cpp(1648) in wxLocale::GetInfo(): Decimal separator mismatch -- did you use setlocale()?If so, use wxLocale to change the locale instead.

#---- End Traceback Info ----# 
```

![image](https://user-images.githubusercontent.com/548413/54086234-eed22800-4347-11e9-8642-f95bed32aa6e.png)
![image](https://user-images.githubusercontent.com/548413/54086241-f7c2f980-4347-11e9-866d-732bc03e6b6f.png)

**Comment by lallulli** [comment]
I will assume this bug has been fixed with the release of Songpress 1.8.0, based on a newer version of wxPython. If not, please reopen the issue.
