### ISSUE TITLE
1.81 on Win 11 gives Error: Something unexpected happened on startup

### ISSUE THREAD

**Issue by jamest-portainer** [lallulli/songpress#58]
I've had Songpress 1.7.2 installed on my last machine on Win 10. Great app.
I got a new machine with Win 11 on and I downloaded and installed Songpress 1.81.
I start up the app and I immediately get the error as per below.
I tried uninstalling and installing 1.7.2 but similar issue.
Also tried running in compatibility mode, but no luck.

**Error: Something unexpected happened**

#---- Notes ----#
Please provide additional information about the crash here

#---- System Information ----#
Songpress Version: 1.8.1
Operating System: Windows 10 (build 22000), 64-bit edition
Python Version: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)]
wxPython Version: 4.1.1 msw (phoenix) wxWidgets 3.1.5
wxPython Info: (__WXMSW__, wxMSW, unicode, unicode-wchar, wx-assertions-on, phoenix, wxWidgets 3.1.5, autoidman, sip-4.19.24, build-type: release)
Python Encoding: Default=utf-8  File=utf-8
System Architecture: 32bit AMD64
Byte order: little
Frozen: True
#---- End System Information ----#

#---- Traceback Info ----#
*** Tue Apr 19 21:23:37 2022 ***
Traceback (most recent call last):
  File "main.py", line 32, in OnInit
  File "C:\Users\Luca Allulli\Documents\dev\songpress\master\src\SongpressFrame.py", line 210, in __init__
  File "C:\Users\Luca Allulli\Documents\dev\songpress\master\src\Preferences.py", line 62, in __init__
  File "C:\Users\Luca Allulli\Documents\dev\songpress\master\src\Preferences.py", line 110, in Load
wx._core.wxAssertionError: C++ assertion "wxFontEnumerator::IsValidFacename(font.GetFaceName())" failed at ..\..\src\msw\settings.cpp(197) in wxSystemSettingsNative::GetFont(): 

#---- End Traceback Info ----#

**Comment by jamest-portainer** [comment]
Seems like this line in Preferences.py doesn't like the wx.SYS_ANSI_FIXED_FONT on my system:
wx.SystemSettings().GetFont(wx.SYS_ANSI_FIXED_FONT).GetFaceName() # "Lucida Console"

Dunno why it has changed, but maybe you could use a try block to catch it and perhaps have a means to read in fonts to use from a configuration file.

Seems to be similar problem in other apps, for instance: https://github.com/robotframework/RIDE/issues/1828

Let me know if there is something I can do to help.

Songpress 1.6 works fine (I think cos it's pre-wxPython).

**Comment by jamest-portainer** [comment]
Anyone out there?

**Comment by jtraxy** [comment]
Your new 1.9.0 version doesn't have this error now, so I think you've fixed it.

**Comment by lallulli** [comment]
Here is the installer: https://github.com/lallulli/songpress/releases/download/1.9.0rc1/songpress-net-setup.exe
